rm cdot.cpp
rm cidot.cpp
rm cimath.cpp
rm cimatrix.cpp
rm cinterval.cpp
rm civector.cpp
rm cmatrix.cpp
rm complex.cpp
rm cvector.cpp
rm cxscmatr.cpp
rm dot.cpp
rm dotio.cpp
rm errtest.cpp
rm except.cpp
rm fi_lib_funcs.cpp
rm idot.cpp
rm imath.cpp
rm imatrix.cpp
rm interval.cpp
rm intmatrix.cpp
rm intvector.cpp
rm ioflags.cpp
rm ivector.cpp
rm j_acos.cpp
rm j_acot.cpp
rm j_acsh.cpp
rm j_acth.cpp
rm j_asin.cpp
rm j_asnh.cpp
rm j_atan.cpp
rm j_atnh.cpp
rm j_cos.cpp
rm j_cosh.cpp
rm j_cot.cpp
rm j_coth.cpp
rm j_erf.cpp
rm j_ex10.cpp
rm j_exp2.cpp
rm j_exp.cpp
rm j_expm.cpp
rm j_lg10.cpp
rm j_lg1p.cpp
rm j_log2.cpp
rm j_log.cpp
rm j_sin.cpp
rm j_sinh.cpp
rm j_sqr.cpp
rm j_sqrt.cpp
rm j_tan.cpp
rm j_tanh.cpp
rm l_cimath.cpp
rm l_cinterval.cpp
rm l_cmath.cpp
rm l_complex.cpp
rm l_imath.cpp
rm l_imatrix.cpp
rm l_interval.cpp
rm l_ivector.cpp
rm l_real.cpp
rm l_rmath.cpp
rm l_rmatrix.cpp
rm l_rvector.cpp
rm lx_cinterval.cpp
rm lx_civector.cpp
rm lx_complex.cpp
rm lx_interval.cpp
rm lx_ivector.cpp
rm lx_real.cpp
rm matrix.cpp
rm matrtest.cpp
rm old_bug.cpp
rm oldinterval.cpp
rm q_acos.cpp
rm q_acot.cpp
rm q_acsh.cpp
rm q_acth.cpp
rm q_ari.cpp
rm q_asin.cpp
rm q_asnh.cpp
rm q_atan.cpp
rm q_atn1.cpp
rm q_atnh.cpp
rm q_comp.cpp
rm q_cos1.cpp
rm q_cos.cpp
rm q_cosh.cpp
rm q_cot.cpp
rm q_coth.cpp
rm q_cth1.cpp
rm q_ep1.cpp
rm q_epm1.cpp
rm q_erf.cpp
rm q_errm.cpp
rm q_ex10.cpp
rm q_exp2.cpp
rm q_exp.cpp
rm q_expm.cpp
rm q_glbl.cpp
rm q_lg10.cpp
rm q_log1.cpp
rm q_log2.cpp
rm q_log.cpp
rm q_pred.cpp
rm q_prnt.cpp
rm q_rtrg.cpp
rm q_scan.cpp
rm q_sin1.cpp
rm q_sin.cpp
rm q_sinh.cpp
rm q_sqr.cpp
rm q_sqrt.cpp
rm q_succ.cpp
rm q_tan.cpp
rm q_tanh.cpp
rm real.cpp
rm realio.cpp
rm rmath.cpp
rm rmatrix.cpp
rm rvector.cpp
rm scimatrix.cpp
rm scivector.cpp
rm scmatrix.cpp
rm scvector.cpp
rm simatrix.cpp
rm sivector.cpp
rm srmatrix.cpp
rm srvector.cpp
rm testclss.cpp
rm test.cpp
rm testdoc.cpp
rm testio.cpp
rm cdot.hpp
rm cidot.hpp
rm cimath.hpp
rm cimatrix.hpp
rm cinterval.hpp
rm civeccmat.hpp
rm civecimat.hpp
rm civecrmat.hpp
rm civector.hpp
rm cmatimat.hpp
rm cmatrix.hpp
rm complex.hpp
rm cvecimat.hpp
rm cvecrmat.hpp
rm cvector.hpp
rm cxsc_blas.hpp
rm cxscmatr.hpp
rm cxscvect.hpp
rm docu.hpp
rm dot_defs.hpp
rm dot.hpp
rm except.hpp
rm fi_lib_consts.hpp
rm fi_lib.hpp
rm idot.hpp
rm imath.hpp
rm imatrix.hpp
rm interval.hpp
rm intmatrix.hpp
rm intvector.hpp
rm ioflags.hpp
rm iveccmat.hpp
rm iveccvec.hpp
rm iveclrmat.hpp
rm ivecrmat.hpp
rm ivector.hpp
rm l_cimath.hpp
rm l_cinterval.hpp
rm l_cmath.hpp
rm l_complex.hpp
rm l_imath.hpp
rm l_imatrix.hpp
rm l_interval.hpp
rm livecimat.hpp
rm liveclrmat.hpp
rm livecrmat.hpp
rm l_ivector.hpp
rm l_real.hpp
rm l_rmath.hpp
rm lrmatimat.hpp
rm l_rmatrix.hpp
rm lrvecimat.hpp
rm lrvecivec.hpp
rm lrvecrmat.hpp
rm l_rvector.hpp
rm lx_cinterval.hpp
rm lx_civector.hpp
rm lx_complex.hpp
rm lx_interval.hpp
rm lx_ivector.hpp
rm lx_real.hpp
rm matrix.hpp
rm real.hpp
rm rmath.hpp
rm rmatrix.hpp
rm rts_real.hpp
rm rvector.hpp
rm scimatrix.hpp
rm scivector.hpp
rm scmatrix.hpp
rm scvector.hpp
rm simatrix.hpp
rm sivector.hpp
rm sparsecdot.hpp
rm sparsecidot.hpp
rm sparsedot.hpp
rm sparseidot.hpp
rm sparsematrix.hpp
rm sparsevector.hpp
rm srmatrix.hpp
rm srvector.hpp
rm testclss.hpp
rm testcomp.hpp
rm testdot.hpp
rm test.hpp
rm testintv.hpp
rm testmatr.hpp
rm testsklr.hpp
rm testvect.hpp
rm util.hpp
rm vector.hpp
rm xscclass.hpp
rm cdot.inl
rm cdotk.inl
rm cidot.inl
rm cidotk.inl
rm cimatrix.inl
rm cinterval.inl
rm civeccmat.inl
rm civecimat.inl
rm civecrmat.inl
rm civector.inl
rm cmatimat.inl
rm cmatrix.inl
rm complex.inl
rm cvecimat.inl
rm cvecrmat.inl
rm cvector.inl
rm cxsc_blas.inl
rm dotk.inl
rm idot.inl
rm idotk.inl
rm imath.inl
rm imatrix.inl
rm interval.inl
rm intmatrix.inl
rm intvector.inl
rm iveccmat.inl
rm iveccvec.inl
rm iveclrmat.inl
rm ivecrmat.inl
rm ivector.inl
rm l_cinterval.inl
rm l_cmath.inl
rm l_complex.inl
rm l_imatrix.inl
rm l_interval.inl
rm livecimat.inl
rm liveclrmat.inl
rm livecrmat.inl
rm l_ivector.inl
rm l_rmath.inl
rm lrmatimat.inl
rm l_rmatrix.inl
rm lrvecimat.inl
rm lrvecivec.inl
rm lrvecrmat.inl
rm l_rvector.inl
rm lx_cinterval.inl
rm lx_civector.inl
rm lx_complex.inl
rm lx_interval.inl
rm lx_ivector.inl
rm lx_real.inl
rm matrix_friend_declarations.inl
rm matrix.inl
rm real.inl
rm rmath.inl
rm rmatrix.inl
rm rvector.inl
rm sparsecdot.inl
rm sparsedot.inl
rm sparseidot.inl
rm sparsematrix.inl
rm sparsevector.inl
rm vector_friend_declarations.inl
rm vector.inl
rm addbody.h
rm a_defs.h
rm a_fcth.h
rm b_64bt.h
rm b_defs.h
rm b_fcth.h
rm b_lari.h
rm b_lpi_.h
rm body.h
rm compiler.h
rm d_defs.h
rm d_fcth.h
rm divbody.h
rm divtrap.h
rm e_defs.h
rm e_fcth.h
rm f_fcth.h
rm l_defs.h
rm l_fcth.h
rm mulbody.h
rm o_defs.h
rm o_fcth.h
rm o_msg1.h
rm o_name.h
rm o_revs.h
rm o_slct.h
rm o_spec.h
rm o_syst.h
rm o_type.h
rm p88rts.h
rm r_defs.h
rm r_fcth.h
rm RtsFunc.h
rm rtsrmath.h
rm RtsTyp.h
rm s_fcth.h
rm subbody.h
rm t_cnst.h
rm t_cond.h
rm t_ddev.h
rm t_defs.h
rm t_drea.h
rm t_exc_.h
rm t_fcth.h
rm t_ieee.h
rm t_mach.h
rm t_name.h
rm y_fcth.h
# manual copy
rm cxscconf.h
rm r_ari.h