# CMake generated Testfile for 
# Source directory: /home/anhvt89/Documents/c++lib/cxsc-2-5-4
# Build directory: /home/anhvt89/Documents/c++lib/cxsc-2-5-4
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(cpz_test_1 "/home/anhvt89/Documents/c++lib/cxsc-2-5-4/CToolbox/test/test_programms/cpz_test" "/home/anhvt89/Documents/c++lib/cxsc-2-5-4/CToolbox/test/test_input/cpz_ex.in1" "/home/anhvt89/Documents/c++lib/cxsc-2-5-4/CToolbox/test/test_vgl_exp/cpz_ex.vgl1" "/home/anhvt89/Documents/c++lib/cxsc-2-5-4/CToolbox/test/test_vgl_exp/cpz_ex.exp1")
add_test(cpz_test_2 "/home/anhvt89/Documents/c++lib/cxsc-2-5-4/CToolbox/test/test_programms/cpz_test" "/home/anhvt89/Documents/c++lib/cxsc-2-5-4/CToolbox/test/test_input/cpz_ex.in2" "/home/anhvt89/Documents/c++lib/cxsc-2-5-4/CToolbox/test/test_vgl_exp/cpz_ex.vgl2" "/home/anhvt89/Documents/c++lib/cxsc-2-5-4/CToolbox/test/test_vgl_exp/cpz_ex.exp2")
add_test(gop1_test "/home/anhvt89/Documents/c++lib/cxsc-2-5-4/CToolbox/test/test_programms/gop1_test" "/home/anhvt89/Documents/c++lib/cxsc-2-5-4/CToolbox/test/test_input/gop1_ex.in" "/home/anhvt89/Documents/c++lib/cxsc-2-5-4/CToolbox/test/test_vgl_exp/gop1_ex.vgl" "/home/anhvt89/Documents/c++lib/cxsc-2-5-4/CToolbox/test/test_vgl_exp/gop1_ex.exp")
add_test(gop_test "/home/anhvt89/Documents/c++lib/cxsc-2-5-4/CToolbox/test/test_programms/gop_test" "/home/anhvt89/Documents/c++lib/cxsc-2-5-4/CToolbox/test/test_input/gop_ex.in" "/home/anhvt89/Documents/c++lib/cxsc-2-5-4/CToolbox/test/test_vgl_exp/gop_ex.vgl" "/home/anhvt89/Documents/c++lib/cxsc-2-5-4/CToolbox/test/test_vgl_exp/gop_ex.exp")
add_test(hess_test "/home/anhvt89/Documents/c++lib/cxsc-2-5-4/CToolbox/test/test_programms/hess_test" "/home/anhvt89/Documents/c++lib/cxsc-2-5-4/CToolbox/test/test_input/hess_ex.in" "/home/anhvt89/Documents/c++lib/cxsc-2-5-4/CToolbox/test/test_vgl_exp/hess_ex.vgl" "/home/anhvt89/Documents/c++lib/cxsc-2-5-4/CToolbox/test/test_vgl_exp/hess_ex.exp")
add_test(jac_test "/home/anhvt89/Documents/c++lib/cxsc-2-5-4/CToolbox/test/test_programms/jac_test" "/home/anhvt89/Documents/c++lib/cxsc-2-5-4/CToolbox/test/test_input/jac_ex.in" "/home/anhvt89/Documents/c++lib/cxsc-2-5-4/CToolbox/test/test_vgl_exp/jac_ex.vgl" "/home/anhvt89/Documents/c++lib/cxsc-2-5-4/CToolbox/test/test_vgl_exp/jac_ex.exp")
add_test(lop_test_1 "/home/anhvt89/Documents/c++lib/cxsc-2-5-4/CToolbox/test/test_programms/lop_test" "/home/anhvt89/Documents/c++lib/cxsc-2-5-4/CToolbox/test/test_input/lop_ex.in1" "/home/anhvt89/Documents/c++lib/cxsc-2-5-4/CToolbox/test/test_vgl_exp/lop_ex.vgl1" "/home/anhvt89/Documents/c++lib/cxsc-2-5-4/CToolbox/test/test_vgl_exp/lop_ex.exp1")
add_test(lop_test_2 "/home/anhvt89/Documents/c++lib/cxsc-2-5-4/CToolbox/test/test_programms/lop_test" "/home/anhvt89/Documents/c++lib/cxsc-2-5-4/CToolbox/test/test_input/lop_ex.in2" "/home/anhvt89/Documents/c++lib/cxsc-2-5-4/CToolbox/test/test_vgl_exp/lop_ex.vgl2" "/home/anhvt89/Documents/c++lib/cxsc-2-5-4/CToolbox/test/test_vgl_exp/lop_ex.exp2")
add_test(lss_test_1 "/home/anhvt89/Documents/c++lib/cxsc-2-5-4/CToolbox/test/test_programms/lss_test" "/home/anhvt89/Documents/c++lib/cxsc-2-5-4/CToolbox/test/test_input/lss_ex.in1" "/home/anhvt89/Documents/c++lib/cxsc-2-5-4/CToolbox/test/test_vgl_exp/lss_ex.vgl1" "/home/anhvt89/Documents/c++lib/cxsc-2-5-4/CToolbox/test/test_vgl_exp/lss_ex.exp1")
add_test(lss_test_2 "/home/anhvt89/Documents/c++lib/cxsc-2-5-4/CToolbox/test/test_programms/lss_test" "/home/anhvt89/Documents/c++lib/cxsc-2-5-4/CToolbox/test/test_input/lss_ex.in2" "/home/anhvt89/Documents/c++lib/cxsc-2-5-4/CToolbox/test/test_vgl_exp/lss_ex.vgl2" "/home/anhvt89/Documents/c++lib/cxsc-2-5-4/CToolbox/test/test_vgl_exp/lss_ex.exp2")
add_test(nlfz_test "/home/anhvt89/Documents/c++lib/cxsc-2-5-4/CToolbox/test/test_programms/nlfz_test" "/home/anhvt89/Documents/c++lib/cxsc-2-5-4/CToolbox/test/test_input/nlfz_ex.in" "/home/anhvt89/Documents/c++lib/cxsc-2-5-4/CToolbox/test/test_vgl_exp/nlfz_ex.vgl" "/home/anhvt89/Documents/c++lib/cxsc-2-5-4/CToolbox/test/test_vgl_exp/nlfz_ex.exp")
add_test(nlss_test_1 "/home/anhvt89/Documents/c++lib/cxsc-2-5-4/CToolbox/test/test_programms/nlss_test" "/home/anhvt89/Documents/c++lib/cxsc-2-5-4/CToolbox/test/test_input/nlss_ex.in1" "/home/anhvt89/Documents/c++lib/cxsc-2-5-4/CToolbox/test/test_vgl_exp/nlss_ex.vgl1" "/home/anhvt89/Documents/c++lib/cxsc-2-5-4/CToolbox/test/test_vgl_exp/nlss_ex.exp1")
add_test(nlss_test_2 "/home/anhvt89/Documents/c++lib/cxsc-2-5-4/CToolbox/test/test_programms/nlss_test" "/home/anhvt89/Documents/c++lib/cxsc-2-5-4/CToolbox/test/test_input/nlss_ex.in2" "/home/anhvt89/Documents/c++lib/cxsc-2-5-4/CToolbox/test/test_vgl_exp/nlss_ex.vgl2" "/home/anhvt89/Documents/c++lib/cxsc-2-5-4/CToolbox/test/test_vgl_exp/nlss_ex.exp2")
add_test(rpe_test_1 "/home/anhvt89/Documents/c++lib/cxsc-2-5-4/CToolbox/test/test_programms/rpe_test" "/home/anhvt89/Documents/c++lib/cxsc-2-5-4/CToolbox/test/test_input/rpe_ex.in1" "/home/anhvt89/Documents/c++lib/cxsc-2-5-4/CToolbox/test/test_vgl_exp/rpe_ex.vgl1" "/home/anhvt89/Documents/c++lib/cxsc-2-5-4/CToolbox/test/test_vgl_exp/rpe_ex.exp1")
add_test(rpe_test_2 "/home/anhvt89/Documents/c++lib/cxsc-2-5-4/CToolbox/test/test_programms/rpe_test" "/home/anhvt89/Documents/c++lib/cxsc-2-5-4/CToolbox/test/test_input/rpe_ex.in2" "/home/anhvt89/Documents/c++lib/cxsc-2-5-4/CToolbox/test/test_vgl_exp/rpe_ex.vgl2" "/home/anhvt89/Documents/c++lib/cxsc-2-5-4/CToolbox/test/test_vgl_exp/rpe_ex.exp2")
add_test(xev_test_1 "/home/anhvt89/Documents/c++lib/cxsc-2-5-4/CToolbox/test/test_programms/xev_test1" "/home/anhvt89/Documents/c++lib/cxsc-2-5-4/CToolbox/test/test_input/xev_ex1.in" "/home/anhvt89/Documents/c++lib/cxsc-2-5-4/CToolbox/test/test_vgl_exp/xev_ex1.vgl" "/home/anhvt89/Documents/c++lib/cxsc-2-5-4/CToolbox/test/test_vgl_exp/xev_ex1.exp")
add_test(xev_test_2 "/home/anhvt89/Documents/c++lib/cxsc-2-5-4/CToolbox/test/test_programms/xev_test2" "/home/anhvt89/Documents/c++lib/cxsc-2-5-4/CToolbox/test/test_input/xev_ex2.in" "/home/anhvt89/Documents/c++lib/cxsc-2-5-4/CToolbox/test/test_vgl_exp/xev_ex2.vgl" "/home/anhvt89/Documents/c++lib/cxsc-2-5-4/CToolbox/test/test_vgl_exp/xev_ex2.exp")
add_test(xev_test_3 "/home/anhvt89/Documents/c++lib/cxsc-2-5-4/CToolbox/test/test_programms/xev_test3" "/home/anhvt89/Documents/c++lib/cxsc-2-5-4/CToolbox/test/test_input/xev_ex3.in" "/home/anhvt89/Documents/c++lib/cxsc-2-5-4/CToolbox/test/test_vgl_exp/xev_ex3.vgl" "/home/anhvt89/Documents/c++lib/cxsc-2-5-4/CToolbox/test/test_vgl_exp/xev_ex3.exp")
subdirs(examples)
subdirs(CToolbox/Programs)
subdirs(CToolbox/test)
subdirs(CToolbox/test/test_programms)
